"""empty message

Revision ID: 80f62742b811
Revises: 446959bd0dda
Create Date: 2020-07-22 12:56:16.513467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f62742b811'
down_revision = '446959bd0dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reports_quiz_id_quizzes'), 'quizzes', ['quiz_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reports_quiz_id_quizzes'), type_='foreignkey')
        batch_op.drop_column('quiz_id')

    # ### end Alembic commands ###
