"""empty message

Revision ID: e685182be921
Revises: 80f62742b811
Create Date: 2020-07-22 15:03:53.661939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e685182be921"
down_revision = "80f62742b811"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("classroom", sa.Integer(), nullable=True))
    op.execute("UPDATE users SET classroom = 99")
    op.alter_column("users", "classroom", nullable=False)
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_users_email")
        batch_op.drop_column("email")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "email", sa.VARCHAR(length=120), autoincrement=False, nullable=True
            )
        )
        batch_op.create_index("ix_users_email", ["email"], unique=True)
        batch_op.drop_column("status")

    # ### end Alembic commands ###
